
package com.tigo.xmlns.tigobusiness.service.getclientaccountgeneralinfomobile.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import com.tigo.xmlns.logheader.v3.LogHeader;
import com.tigo.xmlns.responseheader.v3.ResponseHeader;
import com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobilecountresultsrequest.v1.schema.GetClientAccountGeneralInfoMobileCountResultsRequestType;
import com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobilecountresultsresponse.v1.schema.GetClientAccountGeneralInfoMobileCountResultsResponseType;
import com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobilerequest.v1.schema.GetClientAccountGeneralInfoMobileRequestType;
import com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobileresponse.v1.schema.GetClientAccountGeneralInfoMobileResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PS_GetClientAccountGeneralInfoMobile", targetNamespace = "http://xmlns.tigo.com/TigoBusiness/Service/GetClientAccountGeneralInfoMobile/V1")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.tigo.assettype.v1.ObjectFactory.class,
    com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobilecountresultsresponse.v1.schema.ObjectFactory.class,
    com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobilecountresultsrequest.v1.schema.ObjectFactory.class,
    com.tigo.contracttype.v1.ObjectFactory.class,
    com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobileresponse.v1.schema.ObjectFactory.class,
    com.tigo.xmlns.tigobusiness.getclientaccountgeneralinfomobilerequest.v1.schema.ObjectFactory.class,
    com.tigo.assetservicetype.v1.ObjectFactory.class,
    com.tigo.clienttype.v2.ObjectFactory.class,
    com.tigo.contractprofiletype.v1.ObjectFactory.class,
    com.tigo.plantype.v1.ObjectFactory.class,
    com.tigo.xmlns.clientschema.v1.schema.ObjectFactory.class,
    com.tigo.xmlns.logheader.v3.ObjectFactory.class,
    com.tigo.xmlns.parametertype.v2.ObjectFactory.class,
    com.tigo.xmlns.requestheader.v3.ObjectFactory.class,
    com.tigo.xmlns.requestheader.v3pagination.ObjectFactory.class,
    com.tigo.xmlns.responseheader.v3.ObjectFactory.class,
    com.tigo.xmlns.tigobussines.addresstype.v1.schema.ObjectFactory.class
})
public interface PSGetClientAccountGeneralInfoMobile {


    /**
     * 
     * @param responseBody
     * @param requestBody
     * @param responseHeader
     * @param requestHeader
     * @param logHeader
     * @throws GeneralResponseMessage
     */
    @WebMethod(operationName = "GetClientAccountGeneralInfoMobile", action = "http://xmlns.tigo.com/TigoBusiness/Service/GetClientAccountGeneralInfoMobile/V1/GetClientAccountGeneralInfoMobile")
    public void getClientAccountGeneralInfoMobile(
            @WebParam(name = "getClientAccountGeneralInfoMobileRequest", targetNamespace = "http://xmlns.tigo.com/TigoBusiness/GetClientAccountGeneralInfoMobileRequest/V1/schema", partName = "requestBody")
                    GetClientAccountGeneralInfoMobileRequestType requestBody,
            @WebParam(name = "RequestHeader", targetNamespace = "http://xmlns.tigo.com/RequestHeader/V3pagination", header = true, partName = "requestHeader")
                    com.tigo.xmlns.requestheader.v3pagination.RequestHeader requestHeader,
            @WebParam(name = "LogHeader", targetNamespace = "http://xmlns.tigo.com/LogHeader/V3", header = true, partName = "logHeader")
                    LogHeader logHeader,
            @WebParam(name = "getClientAccountGeneralInfoMobileResponse", targetNamespace = "http://xmlns.tigo.com/TigoBusiness/GetClientAccountGeneralInfoMobileResponse/V1/schema", mode = WebParam.Mode.OUT, partName = "responseBody")
                    Holder<GetClientAccountGeneralInfoMobileResponseType> responseBody,
            @WebParam(name = "ResponseHeader", targetNamespace = "http://xmlns.tigo.com/ResponseHeader/V3", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
                    Holder<ResponseHeader> responseHeader)
        throws GeneralResponseMessage
    ;

    /**
     * 
     * @param responseBody
     * @param requestBody
     * @param responseHeader
     * @param requestHeader
     * @param logHeader
     * @throws GeneralResponseMessage
     */
    @WebMethod(operationName = "GetClientAccountGeneralInfoMobileCountResults", action = "http://xmlns.tigo.com/TigoBusiness/Service/GetClientAccountGeneralInfoMobile/V1/GetClientAccountGeneralInfoMobile")
    public void getClientAccountGeneralInfoMobileCountResults(
            @WebParam(name = "getClientAccountGeneralInfoMobileCountResultsRequest", targetNamespace = "http://xmlns.tigo.com/TigoBusiness/GetClientAccountGeneralInfoMobileCountResultsRequest/V1/schema", partName = "requestBody")
                    GetClientAccountGeneralInfoMobileCountResultsRequestType requestBody,
            @WebParam(name = "RequestHeader", targetNamespace = "http://xmlns.tigo.com/RequestHeader/V3", header = true, partName = "requestHeader")
                    com.tigo.xmlns.requestheader.v3.RequestHeader requestHeader,
            @WebParam(name = "LogHeader", targetNamespace = "http://xmlns.tigo.com/LogHeader/V3", header = true, partName = "logHeader")
                    LogHeader logHeader,
            @WebParam(name = "getClientAccountGeneralInfoMobileCountResultsResponse", targetNamespace = "http://xmlns.tigo.com/TigoBusiness/GetClientAccountGeneralInfoMobileCountResultsResponse/V1/schema", mode = WebParam.Mode.OUT, partName = "responseBody")
                    Holder<GetClientAccountGeneralInfoMobileCountResultsResponseType> responseBody,
            @WebParam(name = "ResponseHeader", targetNamespace = "http://xmlns.tigo.com/ResponseHeader/V3", header = true, mode = WebParam.Mode.OUT, partName = "responseHeader")
                    Holder<ResponseHeader> responseHeader)
        throws GeneralResponseMessage
    ;

}
